import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import LandingPageStyle from './LandingPage.module.css'
import imagenLogo from '../../public/images/logoBlanco.png'

export const LandingPage = () => {

  console.log(imagenLogo)
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={LandingPageStyle.mainBox}>
    <Image
        src="/images/bgWPT.jpg"
        alt="WPT"
        fill
        style={{ objectFit: "cover", zIndex: -1}}
      /> 


      <div className={LandingPageStyle.imageLogoBox}>
      <Image
        src={imagenLogo}
        alt="WPT"
        fill
      /> 
      </div>

      <div className={LandingPageStyle.imageLogoBox}>
        <img src={imagenLogo.src}/>
        <img src={imagenLogo.blurDataURL}/>
      </div>


    </main>
    <div>
      ergergergerihfuiyhfihihih
    </div>
  </>
  )
}
