import React, { useState } from 'react'
import { useTranslation } from 'next-i18next'
import Head from 'next/head'
import Image from 'next/image'
import imagenLogo from '../../public/images/logoBlancoSinLetrasFondo.png'
import LogInScreenStyle from './LogInScreen.module.css'
import {AiOutlineUser} from 'react-icons/ai'
import {AiOutlineEyeInvisible} from 'react-icons/ai'
import {AiOutlineEye} from 'react-icons/ai'


export const LogInScreen = () => {

  const { t } = useTranslation()
  const [showPassword, setShowPassword] = useState(false)
  const [userDataLogin, setUserDataLogin] = useState({
    userName:"",
    userPassword:""
  })




  return (
    <>
      {/* TODO LO CORRESPONDIENTE A POSICIONAMIENTO SEO <Head> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* CONTENIDO GLOBAL DE LogInScreen */}
      <main className={LogInScreenStyle.mainBoxApp}>
        {/* IMAGEN DE FONDO/BACKGROUND */}
        <Image src="/images/bgWPT3.jpg" alt="WPT" fill style={{ objectFit: "cover", zIndex: -1}}/> 

        {/* BOX DE TODO EL FORMULARIO PARA INICIAR SESIÓN */}
        <div className={LogInScreenStyle.LogInFormBox}>
        
        {/* LOGO DEL FORMULARIO */}
        <div className={LogInScreenStyle.logoBox}>
          <img src={imagenLogo.src} style={{height:"100px"}}/>
        </div>

        {/* CAJA QUE AGRUPA USUARIO Y PASSWORD*/}
        <div className={LogInScreenStyle.userPassBox}>

          {/* GRUPO CORRESPONDIENTE A USUARIO*/}
          <div className={LogInScreenStyle.userData}>
            <input type='text' 
              className={LogInScreenStyle.userInput} 
              placeholder={t("LogInScreen_InicioSesion_textoUser")} 
              onChange={(userText)=>{setUserDataLogin({...userDataLogin,userName:userText.target.value})}}/>
            <div className={LogInScreenStyle.icon}><AiOutlineUser/></div>
          </div>

          {/* GRUPO CORRESPONDIENTE A PASSWORD*/}
          <div className={LogInScreenStyle.userData}>
            <input type={showPassword?"text":"password"}
              className={LogInScreenStyle.userInput} 
              placeholder={t("LogInScreen_InicioSesion_textoPassword")} 
              onChange={(userText)=>{setUserDataLogin({...userDataLogin,userPassword:userText.target.value})}}/>
            <div className={`${LogInScreenStyle.icon} ${LogInScreenStyle.cursorP}`} onClick={()=>{setShowPassword(!showPassword)}}>{showPassword?< AiOutlineEye/>:<AiOutlineEyeInvisible/>}</div>
          </div>
          
          {/* BTN INICIO SESIÓN*/}
          <div className={LogInScreenStyle.btnLogin} onClick={()=>{console.log(userDataLogin)}}> {t("LogInScreen_InicioSesion_Button")} </div>

        </div>
        </div>
      </main>
  </>
  )
}
