import React from 'react'
import Head from 'next/head'
import { LogInScreen } from '../LogInScreen/LogInScreen'


export const MainScreen = () => {







  return (
    <>
      {/* TODO LO CORRESPONDIENTE A POSICIONAMIENTO SEO <Head> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LogInScreen></LogInScreen>
      
     
  </>
  )
}
